services:
  produit-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Produitbadia?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      # EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka:8761/eureka
    depends_on:
      - mysql
    networks:
      - microservice-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Produitbadia
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservice-network

volumes:
  mysql-data:

networks:
  microservice-network:
    driver: bridge