server:
  port: 8082  # Port du service de commande
  servlet:
    context-path: /commande

spring:
  application:
    name: Commande-service  # Nom du service pour Eureka

  cloud:
    stream:
      bindings:
        notification-event-out:
          destination: commande.events  # Nom de la destination dans RabbitMQ
          content-type: application/json
      rabbit:
        bindings:
          notification-event-out:
            producer:
              auto-bind-dlq: true  # Active la DLQ pour l'événement en cas d'erreur
        host: localhost  # Hôte RabbitMQ (local dans cet exemple)
        port: 5672  # Port par défaut de RabbitMQ
        username: guest  # Utilisateur RabbitMQ par défaut
        password: guest  # Mot de passe RabbitMQ par défaut
        virtual-host: /  # Hôte virtuel par défaut

  datasource:
    url: jdbc:mysql://localhost:3306/Commande_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root  # Ton utilisateur MySQL
    password:   # Ton mot de passe MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # "update" pour conserver les données existantes
    show-sql: true  # Afficher les requêtes SQL exécutées

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
    register-with-eureka: true  # Enregistrement du service dans Eureka
    fetch-registry: true  # Découverte des autres services
  instance:
    prefer-ip-address: true  # Utiliser l'IP au lieu du hostname

# Configuration Feign pour activer la communication entre services
feign:
  client:
    config:
      default:
        loggerLevel: full
